server:
    error:
        include-message: always
        include-exception: true

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/login_system?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
        username: root
        password: root

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect

app:
    auth:
        tokenSecret: LoginSystemTokenSecretForProgrammingBeginning
        tokenExpirationMillis: 864000000


